### PR TITLE
Describes more options of puppeteer which can help on automation

### PR DESCRIPTION
**Pull request by jfsc**
Hey guys,
This commit is a contribution to help DevOps engineers with automation on OmniScripts. That is just some text which can economize time of reading code to find more options ;)

### CODE REVIEW

**Comment by oxycash** [comment]
We are currently getting below error, it seems this happens if we dont run using these `args: ['--no-sandbox', '--disable-setuid-sandbox'`  but not sure how we can fix these as we, as admin arent writing any Puppeteer code and vlocity has puppeteer embedded. Any way to resolve this? If you have a working docker image, could you share?

image

**Comment by oxycash** [comment]
Regarding executable path, did it ever make difference to you while using puppeteer installed chrome vs self installed chromium? 

Check my discussion once in issues section.

**Comment by jfgarcia268** [comment]
@oxycash You can use this Docker Image jfgarcia268/vlocity_sfdx:latest

**Comment by oxycash** [comment]
Thank you!

Can you share the repo for this as well? Coz I'd need to make changes as per our needs.

**Comment by rutlabaga** [comment]
Sorry I created conflicts here because I was avoiding merging to master. Can you please fix conflicts and create a PR to beta? Otherwise I can also just apply your changes directly to the README if that is not convenient.

**Comment by jfgarcia268** [comment]
@oxycash Sorry for my delay.
Here it is: https://github.com/jfgarcia268/Vlocity-SFI-Docker

**Pull request merged**
